apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trifid.fullname" . }}
  labels:
{{ include "trifid.labels" . | indent 4 }}
data:
  config.json: |
    {
      "baseConfig": "trifid:config-sparql.json",
      "sparqlEndpointUrl": "env:SPARQL_ENDPOINT_URL",
      {{- if or (and .Values.sparql.username .Values.sparql.password) .Values.sparql.existingSecret }}
      "sparqlEndpointAuthentication": {
        "user": "env:SPARQL_USERNAME",
        "password": "env:SPARQL_PASSWORD"
      },
      {{- end }}
      "sparqlProxy": {
        "default": {
          "options": {
            "queryOperation": "postQueryUrlencoded"
          }
        }
      },
      "yasgui" : {
        "default": {
          "template": "cwd:views/yasgui.html"
        }
      },
      "handler": {
        "root": {
          "options": {
            "containerExistsQuery": "ASK { ?s a ?o. FILTER REGEX(STR(?s), \"^${iri}\") }",
            "resourceGraphQuery": "#pragma describe.strategy cbd\nDESCRIBE <${iri}>",
            "containerGraphQuery": "CONSTRUCT { ?s a ?o. ?s <http://www.w3.org/2000/01/rdf-schema#label> ?label. } WHERE { ?s a ?o. OPTIONAL {?s <http://www.w3.org/2000/01/rdf-schema#label> ?label.} FILTER REGEX(STR(?s), \"^${iri}\") }"
          }
        }
      },
      "renderer": {
        "root": {
          "template": "cwd:views/index.html",
          "templateError": "cwd:views/error.html"
        }
      },
      "patchHeaders": {
        "static": {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Expose-Headers": "Link",
          "Cache-Control": "public, max-age=120",
          "Vary": "Accept"
        }
      }
    }
  {{- if .Values.customConfig }}
  custom-config.json: |
    {{ .Values.customConfig | indent 4 }}
  {{- end }}
