{{ if and (not .Values.sparql.existingSecret) .Values.sparql.username .Values.sparql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trifid.fullname" . }}
  labels:
{{ include "trifid.labels" . | indent 4 }}
type: Opaque
data:
  username: {{ .Values.sparql.username | b64enc }}
  password: {{ .Values.sparql.password | b64enc }}
{{ end }}
